### ISSUE TITLE
Can not build master branch

### ISSUE THREAD

**Issue by stanolacko** [TheCodeLabsDevs/CarrotCastle#4]
When trying build master branch (1.1.0), dependency file stl-importer-1.0.0.jar is not downloaded due to HTTP authorization on source of file:
mvn install crash with error:
[ERROR] Failed to execute goal on project CarrotCastleTileCreator: Could not resolve dependencies for project de.thecodelabs:CarrotCastleTileCreator:jar:1.1.0: Could not transfer artifact com.interactivemesh.jfx:stl-importer:jar:1.0.0 from/to release (https://maven.thecodelabs.de/artifactory/Releases): Authentication failed for https://maven.thecodelabs.de/artifactory/Releases/com/interactivemesh/jfx/stl-importer/1.0.0/stl-importer-1.0.0.jar 401 Unauthorized

**Comment by deadlocker8** [comment]
The stl-importer dependency is not published in maven central so for easier use we put it in our own artifactory. Since we didn't want to violate any distribution policies this is not available for non logged-in users.  
You have to install the dependency manually.  
Sadly this library doesn't provide any sourcecode and we are already searching for a replacement.  
The packaged *.jar file can be downloaded from the official website http://www.interactivemesh.org/models/jfx3dimporter.html or to be more specific from http://www.interactivemesh.org/models/download/JFX3DModelImporters_EA_2014-02-09.zip.
  
For manual installation the following command should work:
`mvn install:install-file  -Dfile="C:/dev/jimStlMeshImporterJFX.jar" -DgroupId="com.interactivemesh.jfx" -DartifactId="stl-importer" -Dversion="1.0.0" -Dpackaging="jar"  -DgeneratePom="true"`

**Comment by stanolacko** [comment]
Perfect, it's working now. It will be good to put this information to the README.md file ;-)

**Comment by deadlocker8** [comment]
README extended in aec54ca482d86b1a51fe04fac5222e7a00d5bb3b
